apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-users

resources:
    - ../../base
    - atlas-db-user.yaml
    - configmaps.yaml
    - ingress.yaml
    - middlewares.yaml
    - pod-monitor.yaml
    - secrets/db-creds.yaml
    - secrets/db.yaml
    - secrets/misc.yaml

labels:
    - pairs:
          app: api
          version: v1
          platform: sweetrpg
          package: users
          component: api

generatorOptions:
    disableNameSuffixHash: true
