---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: sweetrpg-users-api
  labels:
    release: prometheus

spec:
  podMetricsEndpoints:
    - port: http
  selector:
    matchLabels:
        app.kubernetes.io/name: users-api
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: users
  namespaceSelector:
    matchNames:
      - sweetrpg-users
