---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: api-v1

spec:
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    selector:
        matchLabels:
            app: api
            version: v1
            platform: sweetrpg
            package: user
            component: api
    template:
        metadata:
            labels:
                platform: sweetrpg
                app: api
                package: user
                component: api
                version: v1
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/path: '/metrics'
                prometheus.io/port: '8000'
                openfeature.dev/enabled: "true"
                openfeature.dev/featureflagsource: "sweetrpg-system/users-api"
        spec:
            serviceAccountName: api
            enableServiceLinks: false
            imagePullSecrets:
                - name: sweetrpg-registry
            containers:
                - name: app
                  image: users-api
                  imagePullPolicy: Always
                  envFrom:
                      - configMapRef:
                            name: api-common
                      - configMapRef:
                            name: api-env
                      - secretRef:
                            name: api-db
                      - secretRef:
                            name: api-misc
                  ports:
                      - containerPort: 8000
                        name: http
                  resources:
                      requests:
                          cpu: "20m"
                          memory: "55Mi"
                      limits:
                          cpu: "1.0"
                          memory: "512Mi"
                  livenessProbe:
                        httpGet:
                            path: /status/ping
                            port: http
                        initialDelaySeconds: 30
                        timeoutSeconds: 10
                        periodSeconds: 10
                  readinessProbe:
                        httpGet:
                            path: /status/ping
                            port: http
                        initialDelaySeconds: 10
                        timeoutSeconds: 10
                        periodSeconds: 10
            restartPolicy: Always
