---
kind: Service
apiVersion: v1

metadata:
  name: api-v1

spec:
    selector:
        app.kubernetes.io/name: users-api
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: users
    type: ClusterIP
    ports:
        - name: http
          port: 8000
          targetPort: http
