---
kind: Service
apiVersion: v1

metadata:
  name: api-v1

spec:
    selector:
        app: api
        version: v1
        platform: sweetrpg
        package: user
        component: api
    type: ClusterIP
    ports:
        - name: http
          port: 8080
          targetPort: http
