---
apiVersion: v1
kind: ConfigMap

metadata:
  name: api-env

data:
  ENV: local
  PORT: "8000"
  BUILD_INFO_PATH: /app/config/build-info.json
  LOG_LEVEL: info
  # OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo-distributor.observability.svc.cluster.local:4318/
  DB_SCHEME: mongodb
  DB_HOST: mongodb.sweetrpg-db.svc.cluster.local
  DB_USER: users-api
  DB_NAME: sweetrpg-users
  DB_OPTS: retryWrites=true&w=majority
