apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-users

resources:
    - ../../base
    - configmaps.yaml
    - secrets.yaml
    - middlewares.yaml
    - ingress.yaml

labels:
    - pairs:
          app: api
          version: v1
          platform: sweetrpg
          package: users
          component: api

generatorOptions:
    disableNameSuffixHash: true

images:
    - name: users-api
      newName: ghcr.io/sweetrpg/users-api
      newTag: latest
